name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        python -m unittest test_timetable_logic.py

    - name: Build with PyInstaller
      run: |
        pyinstaller main.spec --clean --noconfirm

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: NTNU_Course_Query_System_Exe
        path: dist/師大課程查詢系統/